---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- name: Ensure apt key is present for nginx repository
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  become: yes

- name: Ensure nginx apt repository is present
  apt_repository:
    repo: "deb http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx"
    state: present
    filename: nginx
    update_cache: yes
  become: yes

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- include: setup-OpenBSD.yml
  when: ansible_os_family == 'OpenBSD'

# Vhost configuration.
- include: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
