---

- name: Update pkg cache.
  shell: pkg update -f
  when: nginx_freebsd_pkg_update|lower == "yes"

- name: Ensure nginx is installed.
  pkgng:
    name: "{{ nginx_package_name }}"
    state: present

- name: Create logs directory.
  file:
    path: /var/log/nginx
    state: directory
