---
- name: restart nginx
  service: name=nginx state=restarted
  when: not ansible_check_mode

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: reload nginx
  service: name=nginx state=reloaded
  when: not ansible_check_mode
