---
- name: restart nginx
  service:
    name: "{{ nginx_service_name }}"
    state: restarted

- name: validate nginx configuration
  command: "{{ nginx_service_name }} -t -c /etc/nginx/nginx.conf"
  changed_when: false

- name: reload nginx
  service:
    name: "{{ nginx_service_name }}"
    state: reloaded
