---
- name: Converge
  hosts: all
  remote_user: ansible
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 600
      become: yes
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install python packages
      apt:
        name:
          - "python{{ '3' if ansible_python.version.major == 3 else '' }}-dev"
          - "python{{ '3' if ansible_python.version.major == 3 else '' }}-setuptools"
          - "python{{ '3' if ansible_python.version.major == 3 else '' }}-pip"

    - name: Install cryptography python library
      pip:
        name: cryptography
        state: forcereinstall
      tags:
        - nginx

    - name: "Create directories"
      file:
        path: /var/www/{{ item }}
        state: directory
      loop:
        - static
        - media

    - name: "Create test file"
      copy:
        dest: /var/www/{{ item.directory }}/{{ item.file }}
        content: "{{ item.directory }}"
      loop:
        - directory: static
          file: static.html
        - directory: static
          file: cache.js
        - directory: static
          file: cache.css
        - directory: media
          file: media.html
    - debug:
        var: ansible_python
    - name: Run simple python server
      shell:
        cmd: "nohup {{ ansible_python.executable }} -m {{ 'http.server' if ansible_python.version.major == 3 else 'SimpleHTTPServer'}} >/dev/null 2>&1 &"
        chdir: /tmp
