---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: Apache 2.x for RedHat/CentOS/Debian/Ubuntu/Solaris/Suse.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 1.9
  platforms:
    - name: EL
      versions:
      - all
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - precise
      - raring
      - saucy
      - trusty
      - xenial
    - name: Suse
      versions:
      - all
    - name: Solaris
      versions:
      - 11.3
  galaxy_tags:
    - web
